name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: cmake
      run: cmake CMakeLists.txt -B ./out

    - name: cmake build
      run: cd ./out && cmake CMakeLists.txt --build .

    - uses: actions/upload-artifact@v3
      with:
        name: DNX-Note-Width-Changer-${{ matrix.os }}
        path: "./out/bin/Dynamix-chart-width-control*"
