name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: cmake
      run: cmake ./Dynamix_chart_width_control/CMakeLists.txt -B ./out

    - name: cmake build CLI
      run: cmake --build ./out

    - uses: actions/upload-artifact@v4
      with:
        name: DNX-Note-Width-Changer-${{ matrix.os }}
        path: "./out/bin/Dynamix_chart_width_control*"
