name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd "Dynamix chart width control" && make
    - uses: actions/upload-artifact@v3
      with:
        name: DNX-Note-Width-Changer-${{ matrix.os }}
        path: "./Dynamix chart width control/dynamix-chart-width-control*"
